# Generated by Django 5.0 on 2024-05-05 17:47

import Vender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vender', '0003_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical',
            name='average_response_time',
            field=models.FloatField(validators=[Vender.models.Vender.positive_time_in_minutes]),
        ),
        migrations.AlterField(
            model_name='historical',
            name='fulfillment_rate',
            field=models.FloatField(validators=[Vender.models.Vender.positive_percentage]),
        ),
        migrations.AlterField(
            model_name='historical',
            name='on_time_delivery_rate',
            field=models.FloatField(validators=[Vender.models.Vender.positive_percentage]),
        ),
        migrations.AlterField(
            model_name='historical',
            name='quality_rating_avg',
            field=models.FloatField(validators=[Vender.models.Vender.validate_quality_rating_avg]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quality_rating',
            field=models.FloatField(null=True, validators=[Vender.models.Vender.validate_quality_rating_avg]),
        ),
        migrations.AlterField(
            model_name='vender',
            name='average_response_time',
            field=models.FloatField(validators=[Vender.models.Vender.positive_time_in_minutes]),
        ),
        migrations.AlterField(
            model_name='vender',
            name='fulfillment_rate',
            field=models.FloatField(validators=[Vender.models.Vender.positive_percentage]),
        ),
        migrations.AlterField(
            model_name='vender',
            name='on_time_delivery_rate',
            field=models.FloatField(validators=[Vender.models.Vender.positive_percentage]),
        ),
        migrations.AlterField(
            model_name='vender',
            name='quality_rating_avg',
            field=models.FloatField(validators=[Vender.models.Vender.validate_quality_rating_avg]),
        ),
    ]
